import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Link } from "@/src/i18n/navigation";
import { getTranslations } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alabaster Zen",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const t = await getTranslations("nav");

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider locale={locale}>
          <nav className="flex items-center justify-between px-8 py-4 border-b border-gray-100 bg-white">
            <span className="text-sm font-semibold text-gray-900">
              Alabaster Zen
            </span>
            <div className="flex items-center gap-8">
              <Link href="/">{t("home")}</Link>
              <Link href="/about">{t("about")}</Link>
              <Link href="/contact">{t("contact")}</Link>
            </div>
            <div className="flex items-center gap-2 text-xs">
              <a href="/en">EN</a>
              <a href="/ru">RU</a>
              <a href="/tj">TJ</a>
            </div>
            <button className="bg-gray-900 text-white text-sm px-4 py-2 rounded-full hover:bg-gray-700 transition-colors">
              {t("getStarted")}
            </button>
          </nav>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
